### ISSUE TITLE
Consequences of setting "writable" to false for Scripting

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#106]
Let's assume one wants to implement a thing that provides a simple ticketing number system for queuing systems. The idea is that there is a way to get the next available ID but also to allow requesting the "last" ID. Hence incrementing the ID might be done via an action (e.g., `nextId`). Moreover, requesting the last ID could be done through a property and it is explicitly forbidden to set the next `id` directly.

Let me add some code snippets to show an issue.

```
let thing = WoT.produce({
    name: "ticket"
});
thing.addProperty({
	name : id,
	schema : '{ "type": "number"}',
	value : 0,
	observable : true,
	writeable : false /* important */
})

thing.setActionHandler(
	"nextId",
	(parameters) => {
		return thing.readProperty("id").then(function(currId){
			let newId = currId + 1;
			thing.writeProperty("id", newId); /* issue: writing allowed? */
		});
	}
);

/* more like resetting etc */
```

By looking at the code you may have encountered that `thing.writeProperty("id", 123)` will fail. For the scripting runtime it is not possible to know where the call came from and would refuse doing so given to the `writeable : false` statement.

I think the natural way to model this scenario would be a `nextID` action and an `id` property. Anyhow it creates some issues as illustrated above. Any thoughts on this? Shall we simply acknowledge this restriction?

**Comment by zolkis** [comment]
So the use case is to add a property that is read-only, but can be written via an action. The problem is one cannot define that action from outside, since it does not have access to the internal writing method of the Thing.

Since the Scripting API describes the network facing API for a Thing, IMHO for this use case it is best to define a proxy Thing with read-only properties, and defining an action that writes the properties (increment the counter internally and access the property internally).

The problem is we cannot control ownership per property from outside of a Thing (it cannot be even implemented with protocols like OCF).

So I think we should leave the Scripting API as it is.

**Comment by zolkis** [comment]
This is made obsolete by changes in the TD spec (no `writable` any more).
