### ISSUE TITLE
JSONType gaps

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#118]
Besides the type "integer" (as discussed during the Scripting call today) the current definition in https://w3c.github.io/wot-scripting-api/#dom-jsontype misses "null" also.

**Comment by zolkis** [comment]
I thought `null` was not a type, but value.

**Comment by zolkis** [comment]
We also miss the `multipleOf` qualifier from numeric types.

**Comment by danielpeintner** [comment]
> I thought null was not a type, but value.

null seems to be a valid type
http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2.1

Moreover, according to the above section 

> "integer" is a reasonable type for a vocabulary to define as a value for a keyword, but the data model makes no distinction between integers and other numbers

This means, at least for me, we need to do something like this

```
enum JSONType {
    boolean = "boolean",
    number = "number",
    integer = "number",
    string =  "string",
    object = "object",
    array = "array",
    null = "null"
} 
```

I also noticed that some constructs miss optionality.. e.g., minItems and maxItems in array are optional et cetera

**Comment by zolkis** [comment]
All the qualifiers are optional. Maybe we should make `value`, `properties` and `items` required. `type` is already guaranteed to be present.

**Comment by zolkis** [comment]
`"null"` type accepts only one value, `null`. What is the use case for that?

**Comment by zolkis** [comment]
@danielpeintner could you check
https://rawgit.com/zolkis/wot-scripting-api/master/index.html#data-types-used-in-a-thing 

I added `"integer"`, and described how `null` value can be used in initialization.
Also, fixed `Interaction` and `PropertyInit`.
The issue we discussed in the call is moot, since one can associate any property name to a `ThingProperty` when initializing `properties` in an `ThingTemplate` object used in `wot.produce()`, or a `ThingProperty` object used in `addProperty()`.

I noticed that I needed to add a `name` argument to all add...() method in `ExposedThing` (because the way we initialize `ThingTemplate`: `name` is provided separately).

**Comment by zolkis** [comment]
I created #119 as work in progress PR.

**Comment by zolkis** [comment]
Basically the use case is that the `wot.produce()` method needs a template, or a ConsumedThing, or a TD.
When we use a template, `ThingTemplate` contains `properties`, `actions` and `events` that are objects containing a map of names to init dictionaries. Such init dictionary is `PropertyInit`.

Since `PropertyInit` actually implements `ValueType`, they are the same dictionaries: there is no actual moving, only syntactic differences in the way they are described in WebIDL. 

I don't think we can simply move `value` to `PropertyInit`, since an init value can be either a simple `value`, or `items`, or `properties`, depending on `type`. While we could use `any value` as you suggested (and remove `value`, `items` and `properties`), it is underspecified compared to the current way of expressing it. So in theory you are right, but I like the expressivity of the current definitions.

**Comment by danielpeintner** [comment]
I really thing we should NOT mix concepts here. The "value" belongs to the actual instance while a type is simply a type. In the TD specification there is no "value" in the DataSchema definition (see https://w3c.github.io/wot-thing-description/#sec-data-schema-vocabulary-definition),

This brings me to some more more alignments/clarifications:

- We better change "ValueType" to "DataSchema"
- we should also align the actual instances from "NumberValueType" to "NumberSchema"
- once again I think we need a _real_ "integer" enum as done in TD to be consistent
- we might want to also change the enum "JSONType" to "JSONSchemaTypes" to make clear it is NOT about JSON types but about JSON-Schema types

**Comment by zolkis** [comment]
We have used `DataSchema` in the past, but we specify proper objects.

I have made the changes in #119, apart from the name change, and also included a value-matching algorithm. Please check.

I really hate redefining everything that is already defined in JSON Schema. There should be a more minimal way to specify matching. In that case we could have a DataSchema as a string, and apply an external algorithm on the objects (used as init values) against the DataSchema string.

**Comment by danielpeintner** [comment]
I noticed that `ObjectSchema` has property `required`  while `DataSchema` has required also with a different type (--> collision). 

I am wonder why `required` is necessary in base `DataSchema` in the first place....

**Comment by zolkis** [comment]
The way it should be is to have `required` per property, and not per object (as list of strings).

**Comment by danielpeintner** [comment]
I think it should be the other way around. JSON schema has an array of strings for "required" map/object entries.

**Comment by zolkis** [comment]
That way is not good in JavaScript. Since this is a scripting API, implementations should parse the `required` list on the object, and fill in the `required` flags in the properties.

**Comment by zolkis** [comment]
Anyway, these definitions don't _collide_, but are duplication. Perhaps one thing to discuss on the F2F.
IMHO it is perfectly fine to have the JSON Schema way in a TD, and have it the scripting way in the API.

**Comment by danielpeintner** [comment]
Sure, let's discuss this on the F2F.

> IMHO it is perfectly fine to have the JSON Schema way in a TD, and have it the scripting way in the API.

Scripting should be aligned with the TD document. Hence we ought to follow them..

**Comment by zolkis** [comment]
Scripting should be aligned with JS practices. Alignment with TD does not mean 100% identical structures, but compatible structures.

**Comment by danielpeintner** [comment]
with the latest changes (e.g., outsourcing definitions to TD) we can close this issue.
https://github.com/w3c/wot-scripting-api/pull/138
