### ISSUE TITLE
node-wot Korea target implementation experience

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-scripting-api#125]
This is to collect my findings while updating node-wot for the Bundang PlugFest:

* `addProperty()` should take the value separately like `addProperty(name, init, initValue)` to not mix a `value` attribute into the TD/Thing object defitions
* Would it make sense to allow giving the ActionHandler in a similar way as third parameter of `addAction()`?
* We might rather need an extension chain like this: `ThingTemplate` (no instance-specific information to create a new Thing instance) --> `Thing` (has instance-specific fields and can be stringified to a TD) --> `ConsumedThing` (has methods for get/set/run remotely) vs `ExposedThing` (has methods for building/exposing/destroying and get/set/run locally)
* `ThingFilter` cannot use `ThingTemplate`, as one might be looking for instance-specific fields. `ThingFilter` rather needs something like a "Thing Fragment", so something similar to a `Thing` from one above, where all fields are optional

Some spec comments:

> 3.2: Note that this is not the same as the JSON-LD @id attribute

It should be the the `@id`, which is why we put there a URI.

**Comment by mkovatsc** [comment]
* `ExposedThing.emitEvent()` is not required, we would need a `ThingEvent.emit()` when an `ExposedThing` (i.e., not for Events on `ConsumedThing`)

**Comment by zolkis** [comment]
We will need to postpone discussing these to the F2F as both Daniel and me are out in the next 2 weeks. I will eventually add comments/fixes if time permits.

**Comment by mkovatsc** [comment]
* `setPropertyReadHandler()` and -`WriteHandler()` currently has some issues. To solve them, we have to decide between the following to concepts
   * read/write handlers decorate an internal state variable and intercept the value before going out over the binding and before being written to the internal state
      * `PropertyWriteHandler` then would need to return `Promise<any>` to forward the new write value to the internal state. NOTE: This signature must be different from the `set()` function, which must not return the value due to protocol limitations (cf. PUT)
      * `PropertyReadHandler` then would need to take the internal value as argument to do some processing before sending it out. NOTE: This signature must be different from the `get()` function.
   * read/write handlers replace the internal state handling with a custom solution
      * should then be done through a `setPropertyHandlers()` function, to set them as a matching pair
      * can directly replace the `get()` and `set()` functions of ThingProperties

**Comment by zolkis** [comment]
Read- and write handlers are user functions (hooks) on the server side that _define_ what the implementation does when getting a read- or write _request_. Therefore they can encapsulate their internal state management, or internally use `get()` and `set()` as needed.

**Comment by zolkis** [comment]
> addProperty() should take the value separately like addProperty(name, init, initValue) to not mix a value attribute into the TD/Thing object defitions

We can take out the init value from PropertyInit and perhaps also rename it. Actually we don't even need an initValue since it can be initialized by another function (formerly `set`, now `write`). Since when adding properties, the Thing needs to be re-exposed, we don't have a race condition with other write requests in a given script. Also, it makes sense to first add a property _definition_, then initialize it.

**Comment by zolkis** [comment]
> We might rather need an extension chain like this: ThingTemplate (no instance-specific information to create a new Thing instance) --> Thing (has instance-specific fields and can be stringified to a TD) --> ConsumedThing (has methods for get/set/run remotely) vs ExposedThing (has methods for building/exposing/destroying and get/set/run locally)

This intent makes sense to me, let's see how can we formalize it. Instead of `Thing` we could use `ThingInstance`, i.e. ThingTemplate --> ThingInstance --> ConsumedThing --> ExposedThing.

**Comment by zolkis** [comment]
> ThingFilter cannot use ThingTemplate, as one might be looking for instance-specific fields. ThingFilter rather needs something like a "Thing Fragment", so something similar to a Thing from one above, where all fields are optional

Currently it can, but this comment seems to already assume a changed context from above.
In general, in a function that takes an object (dictionary), we can use any other object that contains the same properties. So we need to define ThingInstance as a dictionary, and then we can use it as a ThingFilter.

**Comment by zolkis** [comment]
> ExposedThing.emitEvent() is not required, we would need a ThingEvent.emit() when an ExposedThing (i.e., not for Events on ConsumedThing)

Event modeling is tricky, since there are a lot of them. This explicit function maps easily to whatever event model the underlying runtime supports. Moving to a model that first creates an Event object (to be defined, and harmonized with "native" event models) and then invokes `emit()` on that (assuming it exists) is also a mapping, just a different one, that makes it harder to limit emitting to events on ExposedThing only.

We can rethink Event representation, but starting from clear use cases, and discussing implementation details in the browsers (DOM event model), Node.js runtimes, and others. Until consensus is reached on these, I would stick with the existing explicit function.

**Comment by zolkis** [comment]
> > 3.2: Note that this is not the same as the JSON-LD @id attribute

> It should be the the @id, which is why we put there a URI.

IIRC we discussed this on a TD meeting, where we've got the guidance they are not the same. I am happy if this gets clarified.

**Comment by zolkis** [comment]
> Why should emit() return a promise? It can be called when all required data is available (e.g., when all involved get()s resolve) and it only calls next() on the subject for the observables.

Right, this seems to be the case.

**Comment by zolkis** [comment]
> We might rather need an extension chain like this: ThingTemplate (no instance-specific information to create a new Thing instance) --> Thing (has instance-specific fields and can be stringified to a TD) --> ConsumedThing (has methods for get/set/run remotely) vs ExposedThing (has methods for building/exposing/destroying and get/set/run locally)

Checking on this again. For what use cases do we need an explicit Thing (or ThingInstance) between ThingTemplate and ConsumedThing, how to create it and what to do with it? I don't see use cases where ConsumedThing would not be same or better. Or do you mean to use it as an internal definition instead of ThingModel and possibly as ThingFilter?

**Comment by zolkis** [comment]
Fixed in several PRs, #128, #140 - #143
