### ISSUE TITLE
Consider aligning  the scripting API  (webIDL) with the Interaction vocabulary

### ISSUE THREAD

**Issue by mjkoster** [w3c/wot-scripting-api#127]
For Properties, consider property.read(), property.write() instead of property.get() and property.set()
Also consider property.observe() which returns Observable. 

For Actions, consider action.invoke() instead of action.run()

For Events, consider event.subscribe() instead of reusing observeProperty semantics. It can return Observable.

**Comment by zolkis** [comment]
Name changes to read, write, invoke are fine.

`property.observe()` returning an Observable adds one more indirection but it is fine.

About events, in the TD doc it already reuses property semantics. 
We should then also discuss which Event model (Node, DOM) we support (or define our own).
Currently emitEvent() maps to whatever the underlying platform (JS runtime) supports.

**Comment by mjkoster** [comment]
Maybe returning an observable isn't needed if the object implements observable. I'm not sure I said what I meant. For Events, we have a subscribe method rather than observe. 

Maybe Property has an observe method in addition to read and write, and Event has a subscribe method. That's what I think I meant...

**Comment by zolkis** [comment]
Currently both `Property` and `Event` extend `Interaction` which implements `Observable`, so both Event and Property have a `subscribe()` method. I thought you wanted to use the work `observe()` instead of `subscribe()` for Property for alignment. It is possible, and it could well return an Observable. The problem in that case is that despite of having `observe().subscribe()` the unsubscribing will anyway use the work `unsubscribe()` because of Observable. Defining an explicit `unobserve()` is messy, so the current solution seems to be the cleanest, even though the wording is `subscribe` and `unsubscribe`.

Actually if that is the issue, since we are using our own definition of Observable, we could change the names there: use `Observable.observe()` that returns a Subscription, where one could say `subscription.cancel()` or `subscription.unobserve()`. To avoid confusion with the ECMAScript proposal, we could even rename Observable to something else.

All we need to know how seriously we want to use a given vocabulary, e.g. observe/unobserve vs subscribe/unsubscribe.

We seem to agree that Events should anyway use subscribe/unsubscribe.

**Comment by mkovatsc** [comment]
> For Properties, consider property.read(), property.write() instead of property.get() and property.set()

@mjkoster We ended up with "read" and "write" in the Bindings TF while focusing on the protocol aspects. Yet properties traditionally use "get" and "set" to perform these operations (see also https://en.wikipedia.org/wiki/Property_(programming)).

Since WoT uses exactly this programming abstraction, it would be much cleaner to align in the other direction, that is, fix the terms in Interaction vocabulary -- which I expected to happen for the Korea target.

**Comment by mkovatsc** [comment]
> For Actions, consider action.invoke() instead of action.run()

Here I fully agree. I thought I documented this in another issue, but cannot find it at the moment. Anyhow, we should fix this for the upcoming release.

**Comment by mkovatsc** [comment]
For now, it was most important to align between TD (i.e., forms vocabular, see https://github.com/w3c/wot-thing-description/issues/179) and Scripting API.

For the following reasons, we decided in the call on 6 Aug 2018 to go for `read()` and `write()`:
* get/set usually for synchronous calls
* read/write often used for async calls; we return a promise
* get/set might be in conflict with getters and setters of objects
* we want to allow for easy extension/decoration of the Scripting API to impement over API flavors

I will open an issue for node-wot and do the changes there before the 0.5.0 release.

**Comment by mkovatsc** [comment]
We keep this issue open to see if we can find more and/or better reasons to decide this naming issue.
