### ISSUE TITLE
URI Templates / Variables (Alignment with Binding&TD) 

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#149]
Binding templates (see https://github.com/w3c/wot-binding-templates/issues/44) and TD will allow for specifying and using variables in URIs.

e.g., calling an action with parameters `http://192.168.1.25/left?p=P&d=D`

reminder to implement that capability in scripting also.... e.g., by passing to an `invoke` action besides inputValue also other variables (maybe as a map?)

**Comment by zolkis** [comment]
One option would be to solve this in the TD spec, by adding one more (map) property to [Action definition in TD](https://w3c.github.io/wot-thing-description/#action) in the `input` property (which is an n-ary class). Or a separate  new property besides `input` and `output`.

**Comment by zolkis** [comment]
As discussed in today's Scripting call, the change is needed because 
- the `InteractionPattern` in the [TD](http://htmlpreview.github.io/?https://github.com/w3c/wot-thing-description/blob/td4lyon/index.html) will define `uriVariables`, meaning that URI variables need to be defined when instantiating the Thing and can be referred from all interactions, in addition to their normal parameters, i.e. data provided to Property updates, Action parameters and Events
- allegedly there are already applications that use URI variables for instance named action parameters (examples, links?).

My question to the group: what is the real use case for this?

IMHO the necessity of including low level information on how to construct URI's for queries targeting WoT Things indicates that the WoT's high level abstraction of WoT interactions is fragile.

I hope we would be able to contain this level of details encapsulated in the Protocol Bindings/WoT Runtime and not exposed to high level interactions in scripts. TDs should be written in a way that is able to describe interaction parameters in the already established way.

Otherwise it is more honest to expose WoT interactions only on network API level (that a developer seemingly must know anyway), not on scripting API level (which provides no benefits other than syntactic sugar, but it's fragile because the need to expose new and new information in a way that breaks the API).

**Comment by danielpeintner** [comment]
FYI: It looks like `uriVariables` made it to the TD spec (see https://w3c.github.io/wot-thing-description/#form-serialization-json)

**Comment by danielpeintner** [comment]
I would like to propose 2 possible solutions how the scripting API can support `uriVariables` in interactions. Both proposals have pros and cons (which I tried to list). Please comment what is your favorite or what can be improved.

Let's use as example an action "LeftDown" TD snippet which requires a simple type as input plus some uriVariables (TD properties and events can be done in a similar fashion).

```
"actions": {
    "LeftDown": {
      "input": {
        "type": "number"
      },
      "uriVariables": {
        "p" : { "type": "integer"},
        "d" : { "type": "integer"}
        }
      },
      "forms": ...
    }
```

At the moment the signature of `invoke` would look as follows (in-which the input parameter is optional).

`thing.actions["LeftDown"].invoke(111);`

with no possibility of passing uriVariables.

## Proposal 1

Proposal 1 is about extending the call with a second parameter to pass uriVariables.
Since 2 optional input parameters do not make sense the first input parameter must be set (and set to null if not used).

```
thing.actions["LeftDown"].invoke(111, {
  "p": 0,
  "d": 1
});
```

Pros:
* Does not change input values no matter whether uriVariables are present

Cons:
* makes first parameter required even if not needed

## Proposal 2

Proposal 2 is about *changing* the the existing input parameter to pass `uriVariables` also.

```
thing.actions["LeftDown"].invoke(
      "input": 111,
      "uriVariables": {
        "p" : 0,
        "d" : 1
        }
      }
});
```

To not over complicate the *common* case it should be still possible to pass the input 111 without the "input" structure if NO uriVariables are present/needed.

Pros:
* seems a good match between TD definition and input values

Cons:
* different input structure depending on whether uriVariables are present

I am personally in favor of Proposal 1 but I do not have a very string opinion.
What do others like @zolkis @mmccool @mkovatsc  @mjkoster , ... think?

**Comment by zolkis** [comment]
As we discussed on today's Scripting call, I propose a mix:

## Proposal 3

Extend the `invoke()` call with a second optional parameter to pass an `options` object that contains `uriVariables`. 
```
thing.actions["LeftDown"].invoke(111, { "uriVariables": {
  "p": 0,
  "d": 1
}});
```
Pros: This is aligned with the Web Platform, is semantically more clear when used in a script and it's extensible in the future with other possible options.

**Comment by zolkis** [comment]
With #174, URI variables become encapsulated by the implementation.
