### ISSUE TITLE
WebIDL : attributes vs functions

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#167]
The WebIDL definitions contain *some* attributes besides the function calls.

e.g., see `instance` below

```
interface ConsumedThing {
  Promise<any> readProperty(DOMString propertyName);
  ...
  readonly attribute ThingInstance instance;
};
```

I wonder whether having function calls instead is better (i.e., change `attribute instance` to `getInstance()`).

Doings so offers the possibility to get notified every time the attribte value is called (e.g., for logging) which is not possible with plain attributes (Note: JS offers accessor functions but I don't think this allows the same functionality given that the attributes needs to be there due to the interface also).

Any opinions?

**Comment by zolkis** [comment]
Also see the relevant section of the [TAG Client API Design Principles](https://w3ctag.github.io/design-principles/): [attributes should behave like data](https://w3ctag.github.io/design-principles/#attributes-like-data) and [static vs live object](https://w3ctag.github.io/design-principles/#live-vs-static).

There are a number of pro arguments for attribute (property) being the more natural choice:
- `instance` _is_ data (metadata), exposed for introspection, technically a singleton static object for a given ConsumedThing; its internal structure is that of a complex object and its parts are also accessed as properties, not via functions
- the algorithms work better with `instance` as an attribute (the alternative would be to have an internal slot for `instance`, returned by `getInstance()`, that would result in more complex spec prose, without much gain).
- (IIUR the argument is recursive: if it's not accepted to have `thing.instance` then `thing.getInstance().name` is also discouraged and `thing.getInstance().getName() is preferred) 
- the example code works better with attribute:
`thing.instance.name` vs `thing.getInstance().getName()` 
 `thing.instance.properties['status'].forms.contentType` vs `thing.getInstance().getProperties('status').getForms().getContentType()`.
- by using attribute (property), we can offload constructing a Thing to really constructing an object (fed to `produce()`), instead of specifying a full object creation library that follows the TD spec - such a library is possible, but not in scope of this API [version].
- in the TypeScript implementation of node-wot you could simply say `instance` is `public` and `readonly`:
```javascript
export default class ConsumedThing extends TD.Thing implements WoT.ConsumedThing {
   // ...
    public readonly instance: object;
    constructor(init: object) {
        this.instance = init;
    }   /// ...
};
```
with the caveat that `instance` (`init`) is not by default forced to be immutable: though `thing.instance` is immutable, `thing.instance['name'] can be reassigned, unless built in such way internally (by the implementation) or externally (e.g. by something like `ThingBuilder`). Arguably, building it in that way externally should be out of scope for this API: FWIW in this API `instance` is just data. BTW `getInstance()` doesn't solve the immutability problem per se either, so in both cases it should be enforced by the implementation.

**Comment by zolkis** [comment]
This has been discussed with #174. Closing for now, reopen if needed.
