### ISSUE TITLE
ConsumeThing.instance is misleading

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#176]
Hello, as briefly discussed during WoT Workshop I think that `instance` property of CosumeThing is a little bit misleading. 
Coming from an OO background I would expect that the `instance` property is a relation between a `type` and its instance. I think this is not the case; a ThingInstance is not an instance of CosumeThing but of a ThingDescriptor. 

Perhaps, it would be a better choice to use `thing` instead of `instance` or `description` (?). I know it is a merely formal question but I think it would improve the understanding of the API.

**Comment by zolkis** [comment]
Thank you for filing the issue. The Thing instance meant local updates to the TD from the runtime (not to ConsumedThing or ExposedThing).
However, in the last calls we decided we get rid of the notion since it's confusing in certain contexts.
ConsumedThing will have a property named `td`, instead of `instance`, with slight changes to what it is.
Stay tuned for the new API version that is coming out hopefully today.

**Comment by zolkis** [comment]
Fixed by #174.
