### ISSUE TITLE
handlers for unobserving property/event missing

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#183]
We currently have the following calls.

```
  Promise<void> observeProperty(DOMString name, WotListener listener);
  Promise<void> unobserveProperty(DOMString name);

  Promise<void> subscribeEvent(DOMString name, WotListener listener);
  Promise<void> unsubscribeEvent(DOMString name);
```

When acting as an ExposedThing one gets provided a `WotListener` which gets called on property change or event. Fine so far.

However, I do have issues to understand how *unsubscribing* is meant to work. What if multiple listeners are subscribed? Which one to remove?
I think subscribe methods need to return a handle which than gets passed for unsubscribe...

**Comment by zolkis** [comment]
Right. The current algorithm is that at the client level, in a given script context, there can be only one listener associated with a Property or Event. The new one will overwrite the old one. If one needs multiple listeners, need to duplicate the ConsumedThing object.

The reason for this is to avoid side effects: observing properties and subscribing to events is protocol operation. In a script one can have multiple listeners, but at protocol level, only one listener. If we allow multiple SW listeners, the implementation should invent one listener and remove it when all SW listeners are done. 

Anyway, we can change the current behavior and also provide the `listener` to unobserve and unsubscribe, and implementations should proxy-serve these, managing the underlying protocols as needed. If we choose this, we must outline the algorithms that should be followed.

If I need to take sides, I'd stick with the current mode, i.e. have one listener per property/event.
Do we have use case when multiple SW listeners are needed and from the same ConsumedThing objects? If we had such a use case, we could do it by modifying the existing listener, IMHO.

**Comment by danielpeintner** [comment]
The issue I see is not on ConsumedThing side, but for ExposedThing.

Let's assume I write a "voting" thing exposed on the web. I expose the thing and many would like to observe the thing and get notified for `update`s.
However, after a while some might want to unsubscribe again and call `unsubscribeEvent("update")`.

The ExposedThing implementation gets the notification that "someone" wants to unscubscribe without the actual knowledge *who*.

Do you see what I mean?

**Comment by zolkis** [comment]
But the observe/subscribe API is for clients...

On ExposedThing, the implementation is the one to handle maintaining remote clients (observers and subscribers). The API inherited from ConsumedThing is a (local) client API also on ExposedThing.

The ExposedThing implementation will actually know to identify the clients (based on underlying protocol / binding) since when subscribing, it can and should save the client subscription.

**Comment by danielpeintner** [comment]
I think there is another category, a virtual thing which can be purely a software "exposed" thing.
see https://github.com/eclipse/thingweb.node-wot/blob/next-api-2019/examples/scripts/counter.js

It is a counter thing which can be incremented/decremented etc. Clients can call these actions and can also subscribe to changes (done by other clients).

**Comment by zolkis** [comment]
If we take the title of this issue: the issue is not that these handlers are missing, but that they are encapsulated by the implementation of the ExposedThing.

A purely SW ExposedThing can implement subscriber management the same way as native implementations, just that it will be private to the implementation. 

The rule is, whoever handles protocol bindings will also have to implement subscribers management in the same level. In other words, subscriber management is at same level as protocol bindings. If that is native, then subscribers are handled in native code. If it's JS, then subscribers are handled in JS.

**Comment by zolkis** [comment]
I think what you are after is application-level id of observing and subscribing - subscribe and observe would return an id that is managed by the ExposedThing implementation.

**Comment by zolkis** [comment]
A rationale for exposing subscription id's (from the Scripting call on 19.8.2019):
In embedded use cases it might happen that a script subscribes to a Property update notification, its IP address is changed and then it can no more cancel or get any notifications.

Therefore we'll re-introduce the subscription id's in an upcoming PR.

**Comment by danielpeintner** [comment]
In the scripting API call today the topic was taken up again and we would like to have feedback regarding "it's better to have a subscriptionID for unobserving" or shall it be possible to simply unobserve with the property/event name.

e.g., `unobserveProperty(DOMString propName)` vs. `unobserveProperty(DOMString subscriptionID)`

Do you have an opinion @mkovatsc , @mjkoster, @h0ru5

**Comment by zolkis** [comment]
To summarize the 2 options:
1. Scripts subscribe to names (property, event) and receive a subscription id that can be used for unsubscribing.
2. Scripts subscribe to names (property, event) and unsubscribe from names. The assumption is that the IoT resource running the WoT script will have an identity that implementations can associate the name with, so the id+name acts as a subscription id, the script providing the name and the underlying client side bindings providing the IoT identification. So the Scripting API could "hide" the subscription id behind the name.

Potential issue (with 2): if the underlying IoT identity changes, e.g. an unsubscribe comes from a different IP address, then implementations won't know which subscription to cancel. So there will be an orphan subscription that will consume resources.

Counter-issue (with 1): if any identity/origin (e.g. IP address+port) can cancel an explicit subscription id, that is a potential security issue. (This threat is serious than the previous). So some hardening measures need to be taken that subscription id's are not easily forgeable.

Given this, I think option 1 will always work, but option 2 would be nicer/better/more usable, provided we could always make it work.

**Comment by mmccool** [comment]
I am a little concerned about multiple software packages in a script interfering with one another.   For example, suppose there are two modules (implemented as object) in a single script and a single runtime (thread) which both want to observe the same property.  At the network level, there may only be one transaction for the observe, but at the scripting level I want to make multiple notifications and have subscriptions/unsubscriptions from different object contexts be independent.  In particular I don't want a subscription request from one object/package to clobber (overwrite) a subscription to the same event/property by another unrelated object/package.   So a subscription should return an object or id that I can use to unsubscribe, each subscription request should return a unique such id, and when an external event comes in over the wire, the scripting API implementation needs to send notifications to all objects that have subscribed.

**Comment by zolkis** [comment]
Even though we don't currently support this scenario, but in principle this makes sense, since we could map id+name for any given IoT resource, but not necessarily every subscribing object. 

So let's go with the subscribe id solution (which is in the spec now). 
@danielpeintner can we close?

**Comment by danielpeintner** [comment]
> @danielpeintner can we close?

Yes

**Comment by zolkis** [comment]
After further checking and a discussion with @danielpeintner, the following arguments emerged:
- node-wot actually can already handle the use case in [Michael's comment](https://github.com/w3c/wot-scripting-api/issues/183#issuecomment-529438959), node-wot uses [RxJS subjects](https://rxjs-dev.firebaseapp.com/guide/subject) for this.
- using subscription id's would actually be a big change for node-wot since it would require implementing a similar mechanism but based on externally exposed id's
-since it already handles the use case, the new-old **proposal** is 
> to start without exposing explicit subscription id's and add them only if it becomes an obstacle in other implementations. 

So this subscription-id change will be reverted in the next published version.
