### ISSUE TITLE
*Soften* statements "value MUST be JSON"

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#198]
In [`readProperty()`](https://w3c.github.io/wot-scripting-api/#the-readproperty-method) we do have the statement "value MUST be a JSON value".

@egekorkan pointed me to the fact that based on the contentType the result may be different (see `contentType` other than default value, https://w3c.github.io/wot-thing-description/#sec-default-values).

Hence, I suggest we *soften* this statement.

**Comment by zolkis** [comment]
1. The TD spec says Properties are `DataSchema` (like data format) and `InteractionAffordance` (data context). So everything coming from `forms` in `InteractionAffordance`) should be reflected in `DataSchema`, which follows JSON schema validation, which cannot be overridden by a Form in `InteractionAffordance`, therefore the Scripting spec is correct. 
If there is a gap or conflict, it is in the TD spec.

2. FWIW JSON values can be `string`, `number`, `object`, `array`, `boolean` and `null`.
MIME types can be represented with one of these, if not any other, then a byte `array`.
So I don't see a conflict with `contentType` in `forms` of `InteractionAffordance` class.

3. If we wanted to improve the Scripting API on this, instead of `any`, we could also return a dictionary defined in the WoT Scripting API that would contain e.g. `contentType`, `lang`, `encoding` and `data`. In browser, implementations and scripts could use the [Encoding](https://encoding.spec.whatwg.org/) standard to read (and write) `data`. Of course this also applies for writing Properties.

4. Then, the definition of `contentType` is sloppy/ambiguous in the TD spec.
Depending on the place, it appears to be either of the following:
-- a string denoting a MIME type, such as `application/octet-stream`
-- a MIME type plus encoding
-- a Form (in Default values section).

**Comment by egekorkan** [comment]
I can only answer about the first point:
Actually JSON Schema is used to describe how the data will look like but it does not say that it will be a JSON payload in the end or that it is always used for validation. The concrete words are "It can be used for validation" The binding templates even say that this JSON Schema description can be transformed to an XML Schema and used to e.g. validate XML payloads. (https://w3c.github.io/wot-binding-templates/#mapping-to-xml-schema)

So I would say that if the Scripting API says that values MUST be JSON then the Rotary Beacon Light from Fujitsu would be left out of scope. Its TD is available [here](https://github.com/w3c/wot/blob/master/plugfest/2018-lyon/TDs/Fujitsu/Fujitsu-RotaryBeaconLight.jsonld). There is also the Intel camera that returns image/jpeg (line 1000 in [here](https://github.com/w3c/wot/blob/master/plugfest/2019-tpac-fukuoka/TDs/Intel/intel-camera.json)) where it doesn't even need data schema since contentType is enough to describe the value. Actually, in this case, things get even more complicated since the term value doesn't sort of fit here.

node-wot (https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/content-serdes.ts) also supports receiving text/plain on the Consumer side

**Comment by zolkis** [comment]
First, the TD spec should be more exact about data types, validation etc. If `DataSchema` can define one of object, array, string, number, integer, boolean, or null as `type`, then that's it. Please fix the TD spec. IMHO the whole data handling in the TD spec would be worth revisiting.

Then, as I said, MIME types can be easily represented even now (though improvement possible, see above). The `forms` array might contain information about the `contentType` and that's how the data will be decoded.

I don't understand why the Rotary Beacon Light would be left out of scope, its data can be read as a string (btw, is it correct? it has `mediaType`, not `contentType`).

The camera data can be represented as a byte array (BAIS, or base64). Of course this can be improved for efficiency. 

The proper way would be a Scripting-defined `Value` dictionary like the one above (and below): currently we need those 4 properties in the Web Platform to represent binary or textual data with encoding and language. 

So this is my proposal to handle values in WoT _Scripting_:

```javascript
interface Value {
  readonly attribute USVString? mediaType;
  readonly attribute USVString? encoding;
  readonly attribute USVString? lang;
  readonly attribute DataView? data;
}
```
Then we can create/read text, JSON or binary by choosing the encoder/decoder.

**Comment by danielpeintner** [comment]
In Scripting teleconference on 2019-12-16 we decided to remove "value MUST be JSON" based on the pending PR https://github.com/w3c/wot-thing-description/pull/869.

The idea is to redo the algorithm of `readProperty()`. value must comply to
1. content type
2. if data schema definition is present, value must comply also.

**Comment by zolkis** [comment]
Superseded by #201, closing.
