### ISSUE TITLE
Update references to upcoming documents

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#278]
Update links to most recent documents
* TD 1.1.
* Architecture 1.1
* ...

**Comment by zolkis** [comment]
Do they need to be published first?

**Comment by danielpeintner** [comment]
once the publication date has been decided we can fix the dated URIs in advance..

**Comment by zolkis** [comment]
While participating in other groups, there was a recommendation to link against the most recent version of any spec, since people are always checking if there is a more recent version of the document than the one linked. Exception when we point to a discontinued term, but that should be in a <a href=""></a> tag. This is used in the Web Platform in general.

**Comment by zolkis** [comment]
For now we can link the named versions, as agreed in the call, but I'd like that we revisit this in the future.

**Comment by danielpeintner** [comment]
> While participating in other groups, there was a recommendation to link against the most recent version of any spec

I don't really have a strong preference but all WoT specs should do the same and it seems they link to dated URIs (see https://www.w3.org/TR/wot-thing-description/#bib-wot-architecture)

**Comment by relu91** [comment]
In the terminology section, I've just noticed that only some terms are linked back to the Thing Description document. Should we fix this?

**Comment by danielpeintner** [comment]
> In the terminology section, I've just noticed that only some terms are linked back to the WoT Architecture document. I'm referring to this [paragraph](https://w3c.github.io/wot-scripting-api/#dfn-things). As you can see most of them are not linked but _DataSchema_ and _Form_. Should we fix this?

I think we should add the links. I see 2 downsides though
1. The para starts with "the generic WoT terminology is defined in [WOT-ARCHITECTURE]" but later we point to the TD document
2. Adding the links creates yet another place were we need to update the links to the dated URI (at the moment it uses the TR link)

**Comment by zolkis** [comment]
IMHO all this versioned link thing is not needed. What matters that at any point in time, the WoT specs are relatively up to date vs each other. That is already ensured by the publication process.

IMHO we should always link to the github.io versions, and use links in abundance since it's convenient. More convenient then click -> go to references -> click -> good luck to find what you want vs just click :).

The references could (and I think actually must, per publication rules) use the versioned links. We can clarify that on the next call.
@ashimura ?

**Comment by zolkis** [comment]
In the Scripting call today there were 2 opinions we should use generic links (not dated), since readers tend to check the latest versions of W3C specs anyway. However, it was pointed out that TR versions are always (de factor) dated and are tracking divergent development in a more consistent way. 
The issue can be closed after publication.

**Comment by ashimura** [comment]
PR #288 covers this issue as well.
