### ISSUE TITLE
Synchronization use cases

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-scripting-api#28]
As discussed on the Scripting call, we have a number of use cases for Thing replication and synchronization. Some of these may require additions to the Scripting API. Please contribute with use cases.

**Comment by zolkis** [comment]
Some of the *use cases*:
- Thing2 acts as a proxy to Thing1 (to be expanded)
- Thing2 acts as a reverse proxy to Thing1 (to be expanded)
- ThingX is a composite made from bits of Thing1, Thing2, ...

Some of the *mechanisms*:
1. create a Thing2 "similar" to a Thing1: has properties, actions, events with the same name, and signature; state (property values, internal slots* etc) are not replicated. When we generate a TD, it contains all function (action, event handler) signatures.
2. create a Thing2 as exact runtime copy of Thing1, like in 1), but replicating state as well.
When we generate a TD, it has to contain the serialized action and event handlers.
3. create Thing2 as an _extension_ of Thing1 (overloading possible); like in 2), but TD _contains_ the TD of Thing1

*The notion of ["internal slot"](http://ecma-international.org/ecma-262/6.0/#sec-object-internal-methods-and-internal-slots) to an object is defined in ECMAScript, but not specifically in WoT. Arguably all relevant state of a Thing should be exposed as properties.

**Comment by mjkoster** [comment]
I'm not sure I was using the terms forward and reverse proxy in the usual sense. Most of what we are talking about is reverse proxy for shadow things, from the client's point of view.

Consider the case where Thing1 updates its state using a private API, and Thing2 updates its state by observing Thing1

State synchronization of Thing2 to Thing1's state could be done by embedding a client in thing2 that observes Thing1. The client would observe Thing2, and Thing2 would in turn observe Thing1.

This is a reverse proxy pattern, because the origin (Thing1) updates the cache/shadow (Thing2) and client interacts with the cache/shadow as if it were the origin.

If Thing2 exposes Actions for the client to invoke, which in turn invoke Actions on Thing1, it is still a reverse proxy from the client's point of view, since the client invokes the action on Thing2 as if it were Thing1.

Forward proxy would be adapting the application client to the proxy client without a shadow set of resources.

**Comment by mjkoster** [comment]
The reverse proxy use case would involve the client being able to do get/set/observe of properties, invocation of actions, and subscription/management of events on Thing2 as if it were interacting with Thing1. 

The forward proxy use case would be to have a set of controls that the client would need to use to interact with Thing1 but would synchronize directly between Thing1 and the client state without a "shadow" Thing2.

I think we are talking more about the reverse proxy case in synchronization, correct?

**Comment by knimura** [comment]
I also think we are talking about reverse proxy.

* Thing2 act as a reverse proxy to Thing1
  The state synchronization can be achieved by observing Thing1.

  * Expansion 1: Even when Thing1 loose the power, Thing2 holds the state and replicate as an additional feature.

  *  Expansion 2: Thing2' provides extended features of Thing2.
  e.g. add features that does not have in Thing1 and provide the API.

* ThingX is a composite made from Thing1, Thing2,...

**Comment by mkovatsc** [comment]
> When we generate a TD, it has to contain the serialized action and event handlers

It sounds like you are mixing up descriptions for Things and container formats for Scripts.
TDs must not contain any code for action handlers or the like.

When something that looks similar to a TD has code snippets, we should call it something else, as it is then an alternative representation of a script, a declarative approach to implement a a Thing opposed to imperative containing the addProperty() etc. calls).

**Comment by zolkis** [comment]
> It sounds like you are mixing up descriptions for Things and container formats for Scripts.
TDs must not contain any code for action handlers or the like.

Maybe so. I was thinking about the use case when you want to extend a Thing's existing action, so there should be a way to call the base action. Of course that can be achieved by other means, or it's also possible this use case should be solved in some other way. Suggestions welcome.

**Comment by mkovatsc** [comment]
Okay, sorry for the side track; it just turned out that these misunderstandings in terminology cause the most confusion or "disagreement" due to mismatch of terminology.

Anyhow, the given use cases are all "reverse proxies", that is, they look to the client like the origin(al) server/Thing. And I agree on the following three possibilities:
1. Proxy Things in the sense to simply forward requests; this might also include techniques such as caching, but the TD would stay the same apart from link URIs and maybe communications metadata (once we have this...)
2. Augment Thing by overriding the Interactions (e.g., perform checks on Property writes, add some procedure to an Action invocation). This might need additional semantic annotations or even changes in the TD.
3. Compose multiple Things and present it as a single Thing, potentially with Interactions of higher order (one Property write results in a write to all Things, Action invocation invokes Actions of one or two specific Things in the composition). This basically needs a mashed up or even completely new TD.

I would focus for now on the simple proxy case (1.) as it is the only one that can be generalized to derive the first standardized management vocabulary.

Cases 2. and 3. are basically like designing a Thing from scratch. You need to know what you are doing and create the TD accordingly. In the future, experience what kind of augmentations or compositions are needed in most cases to derive some default cases. This in turn can then lead to the next set of standardized vocabulary.

**Comment by mkovatsc** [comment]
Most important: I don't see why this would need specific additions in the API. It's all implementable by consuming and exposing Things.

I would not assume that everyone wants to realize these proxies in the same way, so that decisions on this end up in the core design of the runtime. They should be more considered just like individual Things that someone implemented. Let's focus on a versatile, stable core and do specialized convenience functions once there is enough experience (in maybe 10 years...).

**Comment by zolkis** [comment]
The API would not change, but the TD yes. When in doubt, let's select less features (so I am fine with case 1), but as forward compatible / extensible with possible/expected changes as possible.

**Comment by knimura** [comment]
I agree, case 1 is the core use case we should target on.

**Comment by zolkis** [comment]
This discussion can be marked complete for the current charter.
