### ISSUE TITLE
Improve the Form selection algorithms

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-scripting-api#282]
Currently the first Form found that matches the `op` field is used. 
See for instance step 4 in the [reading algorithm](https://w3c.github.io/wot-scripting-api/#the-readproperty-method).
We should consider allowing to loop through all Forms and selecting the best match.

**Comment by danielpeintner** [comment]
I see the point. On the other picking the *right* form should be up to the runtime due to load balancing or any other reason.

IF the consumer wants to pick a specific `formIndex` it can be done so already.
Hence I am opposed to go along this path...

**Comment by relu91** [comment]
> I see the point. On the other picking the right form should be up to the runtime due to load balancing or any other reason.

My question is: if one form fails due to a connection error, should the runtime try the second form in the list?

**Comment by danielpeintner** [comment]
> My question is: if one form fails due to a connection error, should the runtime try the second form in the list?

Good question ;-)

I can see pros and cons
* in some environments if a device is down it does not make sense to iterate over all possible IPs, bindings et cetera since it won't help
* in other use-cases it might help (e.g., DNS is down but IPs still work fine..)
* ...

I wonder whether it is acceptable to shift the choice to the consumer again (just like we do with `formIndex`).
The consequence *could* be
* leaving it as is since a consumer could specify all possibles indices step-by-step OR
* come up with a `retry` option that indicates to the runtime it should do its best to find a _working_ form

Personally I am more in favor of leaving it as is but I am open to other opinions.

**Comment by zolkis** [comment]
I am also inclining to leave the selection algorithm to the implementations. So I will modify that step to NOT say "pick the first Form whose `op` is matching", but instead make clear the impl can choose to loop over, try multiple Forms etc. What should be clear though is how it fails and how it goes on when succeeds.
