### ISSUE TITLE
Publish Thing Description schema and Types in another npm package

### ISSUE THREAD

**Issue by relu91** [w3c/wot-scripting-api#327]
As observed in https://github.com/WebThingsIO/gateway-addon-ipc-schema/issues/19#issuecomment-877100054, one problem of the current publication strategy is that it is not clear which version of the Thing Description Schema is bundled in `wot-typescript-definitions package. In addition, projects that just want to use TD types for validation and loading need to carry over also the definitions for the scripting API. 

My suggestion is to split the current package in two:
- wot-api-types (or keep the current naming)
- wot-thing-description-types

Opinions?

**Comment by egekorkan** [comment]
just one small comment, the td schema is published on npm via playground at https://www.npmjs.com/package/@thing-description-playground/core

**Comment by relu91** [comment]
Interesting, would you evaluate using a `wot-thing-description-types` that are semi-automatically published using the action in this repository instead of shipping the schema inside the core package?

**Comment by egekorkan** [comment]
Yes it would be possible. The schema is automatically tested upon a PR made to the playground repo.

**Comment by danielpeintner** [comment]
Some comments (no strong preference) 
* the overhead of having the API besides the required types seems _negligible_ ... this boils down to the fact that there should be a way to identify the ThingDescription Schema version (a way to identify API version seems reasonable also)
* _outsourcing_ the types is fine by me also. w.r.t. naming I would prefer not to change the naming (of the current npm package).

**Comment by relu91** [comment]
So assume I have this need: 
- I want to use a Thing Description in my project (idk I want to build a tool that adds to every TD funny stuff)
- In the current situation I have to install `wot-typscript-defitions:0.8.0-SNAPSHOT-X` 
- It is not clear to which TD version I am pointing to, I have to lookup 
- If I need an older version is even harder to understand which one I need to import
- I give up and I decide to do copy and paste the schema 

I know is kinda a small detail, but I feel it makes the difference between a good dev experience and a bad one. 

*Note*: this is also valid for the playground package, right? IMHO the cleanest solution is to have a dedicated package.

**Comment by danielpeintner** [comment]
I agree, developer experience is important.

I think this boils down to a proper description (also history) and what a certain version actually means.
Having `1.1.0-DATE` or similar **alone** does net help. A developer may be interested in the actual change...

Let me propose the following steps forward:
1. Split types from the API
   * create `wot-thing-description-types` for the TD types
   * keep `wot-typescript-definitions` for the API (for simplicity and backward compatibility)
2. Come up with a proper versioning scheme
   * for `wot-thing-description-types`: using TD version a la `1.1.0-DATE` for TD1.1 development and have a final version `1.1.0`
   * for `wot-typescript-definitions`: _here I am unsure how to proceed best since the API may evolve independently from the TD. Keep the current versioning?_  
3. Document on the dedicated [README.md](https://github.com/w3c/wot-scripting-api/blob/main/typescript/README.md) the history of  the versions (the readme will be propagated to [NPM](https://www.npmjs.com/package/wot-typescript-definitions) also). Same for the new `wot-thing-description-types`.

Does this make sense? Other proposals?

**Comment by relu91** [comment]
I like the plan. Few comments:
- on 2 I think it's okay to keep the current schema for the API. 
- About 3 why don't we use the tag functionality of Git and Github? the versions will be listed cleanly. Plus also npm has a version list. The readme file feels redundant and difficult to keep in sync.

**Comment by danielpeintner** [comment]
>  * About 3 why don't we use the tag functionality of Git and Github? the versions will be listed cleanly. 

This could work but at the moment the GitHub commit message is simply the same message always ("chore(typescript): sync json schema from wot-thing-description.git ", see https://github.com/w3c/wot-scripting-api/commit/98e7421ca193998861bb3703a7c708608d2916b6)

Moreover, I think the work to manually copy over the commit/change message from TD repo is doable.
If it can be automate even better!

> Plus also npm has a version list. The readme file feels redundant and difficult to keep in sync.

The [version list](https://www.npmjs.com/package/wot-typescript-definitions?activeTab=versions) is there but it does not provide good input what has been changed. This may also depend on how we commit the update...

**Comment by danielpeintner** [comment]
Scripting call 2021-07-19
@relu91 will work on PR together with @danielpeintner

**Comment by egekorkan** [comment]
Regarding the comment by @relu91 above:

> Note: this is also valid for the playground package, right? IMHO the cleanest solution is to have a dedicated package.

This gets a bit tricky. I want to strictly abide by the semantic versioning rules for the playground. If a new feature gets added, the minor version should be incremented. The major version should be aligned with the major TD versions. When TD 2.0 arrives with breaking changes, the `validate()` function would also have a breaking change.

**Comment by benfrancis** [comment]
Just a thought, but should the official JSON schema (and possibly TypeScript types) for Thing Descriptions not live in the wot-thing-description repo rather than the wot-scripting-api repo? It's not really specific to the scripting API.

That might also help to keep them in sync (I noticed several commits syncing the two as I added new terms to the TD specification).

**Comment by relu91** [comment]
> Just a thought, but should the official JSON schema (and possibly TypeScript types) for Thing Descriptions not live in the wot-thing-description repo rather than the wot-scripting-api repo? It's not really specific to the scripting API.

I first proposed to have the types on the TD repo, but the consensus was to move them here mostly because in the scripting-api we have already a process in place to publish npm packages. Currently, there's a GitHub action that syncs the JSON schema file nightly (but it seems to fail now, I have to look at it). I also proposed to automatically publish the generated types, but again the consensus was to make an automatic issue published by the Github action asking for publishing.

**Comment by zolkis** [comment]
> Just a thought, but should the official JSON schema (and possibly TypeScript types) for Thing Descriptions not live in the wot-thing-description repo rather than the wot-scripting-api repo?

I agree (in principle). In practice, @relu91 explained the reasons. But it's possible to re-discuss.
