### ISSUE TITLE
Rename Use Cases section ?

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#355]
In the editors calls @mlagally raised concerns that the current "[Use Cases](https://w3c.github.io/wot-scripting-api/#use-cases)" section might conflict with the [use-cases document](https://w3c.github.io/wot-usecases/).

There were proposals floating around to rename it to something like "Scenarios" (that require certain capabilities)

Any thoughts?

**Comment by zolkis** [comment]
This section is about use cases _for scripting_. It might pull stuff from the use cases doc. No conflict in my view.

**Comment by zolkis** [comment]
Other API specifications are using a section "Use cases", and is recommended for TAG reviews etc. They are not going to go to massive external documents to gather tiny bits for a given spec. What is relevant to Scripting should be in the Scripting spec.

**Comment by danielpeintner** [comment]
Scripting Call 2021-11-29
1. Option: Use "Features" term  (1 vote)
2. Option: Other APIs use "Use Cases" section, use Disclaimer in section to link wot-usecases 
   - Generic WoT use-cases .. link to wot-usecases document
   -  Derived use-cases in this spec (2 votes)
 
TODO: re-check in editors call...
@mlagally can you say whether option 2 is a possible alternative

**Comment by chachamimm** [comment]
"Use Cases" is  a specific situation in which a product or service  potentially be used. But this section is about features for scripting. Therefore This Section should be "Features".

"Use Cases" for scripting should be referenced from "Use Cases" for other WoT documentations. I think  it is more necessary to describe features and usages for Scripting API than Use Cases for Scripting API.

**Comment by danielpeintner** [comment]
Scripting API Call 2021-12-06
* Consistency with other documents is key
* "Functionalities"+2.5  vs "Features"+2

@zolkis  are you ok to go with one of the aforementioned terms?

**Comment by chachamimm** [comment]
I checked the difference between "Functionalities" and "Features". "Functionalities" includes "Features".

Therefore, I will change my opinion from "Features" to "Functionalities".

**Comment by zolkis** [comment]
We need to follow other Web specifications vocabulary here.
We could say "Developer use cases", or "Scripting use cases".
"Features" is not really what they are. 
"Functionalities" is a really bad word, we'd rather remove the whole section then.

TBH I don't see what this "conflict" is about and why developer/scripting use cases is not suitable.

**Comment by danielpeintner** [comment]
Note 1: I don't think we should remove the section. It is useful to see what is supported by the Scripting API.
Note 2: People in the WoT (outside of your taskforce) seem to have a different expectation when reading "use cases" -> we should avoid conflicts. It is not about the name but the content of the section is of importance.

Hence, I still think we should try to find another term. Let me throw in another term: "Supported Features".
As said in the call, either of the terms is fine by me.

**Comment by zolkis** [comment]
Use cases is a common word, like architecture.
Every entity that has an architecture, also has use cases and requirements, in a given context.
https://en.wikipedia.org/wiki/Use_case 

The Use Cases document contains system deployment scenarios in a number of domains, i.e. business and system use cases.
The Scripting use cases are relative to developer use case scenarios.
Different context (namespace), no conflict, i.e. false conflict.

Whether we rename or not the section should be not for this reason.

To be exact, the use Cases document should be named more specific (business and system use cases), whereas in the Scripting spec they could be called "scripting use cases".

The terminology of use cases is important because it is part of drawing requirements, thus architecture. It's a known process. Renaming one element in a known process will cause more confusion than reading "use cases".

BTW I hope we can still use the word "architecture" in the spec, as we also have a WoT Architecture spec. I hope people are not confused by that one.

**Comment by danielpeintner** [comment]
I am concerned about the content and I believe it should stay. If some people are not happy with the term "use case" in our document we should try to find a solution. I think a way forward is to rename it...even though I don't think it is an issue as it is now.
Having said that, I don't think it is worthwhile fighting for the term either...

**Comment by zolkis** [comment]
Some people should add the local ("scripting") namespace to "use cases", it should be clear that it pertains to the document scope, and not replacing the system use cases (which should also change name, to be clear).
We could also make it clear, like
- Developer use cases (in short: use cases)
- Scripting use cases (in short: use cases)
- Features (though this is not used in web specs, they tend to take features/use cases and place them in separate sections).

I think we could go by "Features", but it's not accurate. "Use cases" continues to be the best term and there should be no confusion, as the (relatively short) content makes it clear right away. No clashes with the WoT Use Cases document that I can see. Or could someone point out what actually is clashing?

**Comment by zolkis** [comment]
We could keep "Use Cases" and link to the WoT system use cases in the first sentence. Then introduce developer use cases, as stated in the section.

**Comment by mlagally** [comment]
Could you please walk through the use cases and requirements document and see which of these use cases are applicable for Scripting? We have the "Dependencies" headline, which could also reference the scripting spec.

**Comment by mlagally** [comment]
> Scripting Call 2021-11-29
> 
> 1. Option: Use "Features" term  (1 vote)
> 2. Option: Other APIs use "Use Cases" section, use Disclaimer in section to link wot-usecases
>    
>    * Generic WoT use-cases .. link to wot-usecases document
>    * Derived use-cases in this spec (2 votes)
> 
> TODO: re-check in editors call... @mlagally can you say whether option 2 is a possible alternative

@danielpeintner , sorry, I missed your previous question. Please see above.

**Comment by zolkis** [comment]
> Could you please walk through the use cases and requirements document and see which of these use cases are applicable for Scripting?

None apply, since (as explained above) those are business/system use cases, and in the Scripting spec there are developer use cases (like system architecture vs component architecture). The latter can be used for implementing the former. Disjunct context, set, etc. Both can be called use cases in their context. The reason they'd need to be called "use cases" also in Scripting was explained above as well: from use cases come requirements, from them come features, from them come the API. We need these to justify the API shape. However, there are specs that don't have a named "Use Cases" section, instead they are dedicating a section per use case, and also present the API fulfilling that use case. We have not followed the latter in the Scripting spec. We have a dedicated section for scripting use cases.

In order to make it very clear, as also explain above, we could add a sentence in the beginning of the section to link to the business/system use cases and explain the following (scripting) use cases to implement the former.

**Comment by relu91** [comment]
Renaming to "Developer use cases" is still on the plate? I would support that. 

> In order to make it very clear, as also explained above, we could add a sentence in the beginning of the section to link to the business/system use cases and explain the following (scripting) use cases to implement the former

I think this does not hurt either. 

> Could you please walk through the use cases and requirements document and see which of these use cases are applicable for Scripting? We have the "Dependencies" headline, which could also reference the scripting spec.
If you identify use cases with relevance for scripting, ideally we update the use case document and add scripting to the "Dependencies" before we publish it.
The deadline for document freeze however is coming close, i.e. we want to close the document next Tuesday.

[Section 3](https://www.w3.org/TR/wot-usecases/#sec-horizontal-ucs) might be a good place. Discovery is already there, but I agree with @zolkis it is not really the best fit cause we have a different target audience...

**Comment by danielpeintner** [comment]
Scripting API Call 2021-12-13
* @ashimura to talk with @plehegar  about the name, "Developer use case", "Features", "Functionalities", ..
* explain the different use-cases and link use-cases document

**Comment by ashimura** [comment]
I got clarification from @plehegar and the conclusion is:
* We'd suggest to use "Scenarios" instead of "Use Cases" here.
* However, we don't really have any clear definition for "Use Cases" itself.
* So probably we could use "Use Cases" on the API level as well if we really want to use term to show the typical scenarios of API usages.

However, we should define that (=API-level use cases) clearly if we use the term :)

**Comment by zolkis** [comment]
I am fine with "Use case scenarios" or "Developer use case scenarios" or "Scripting scenarios".
Plus for including a comment explaining the difference from the WoT Use Cases document, lest anyone mixes them up. :)

**Comment by danielpeintner** [comment]
Scripting Call 2022-01-31
* @zolkis volunteers to create PR
