### ISSUE TITLE
The future of the conformance class WoT Discovery

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#396]
We recently had an internal discussion about the conformance class WoT Discovery.

The *current* discovery functionality is limited to the [discovery methods](https://w3c.github.io/wot-scripting-api/#the-discoverymethod-enumeration).
* direct
* directory

This seems to be more a convenience function than an actual help.
* direct -> could be done else-wise
* directory -> the TD for Directory should be a Thing Model, see https://w3c.github.io/wot-discovery/#directory-api-spec

Note: local discovery is planned to be added again.

The WoT discovery  process is divided into two phases
* Introduction (set of URLs, not including any security or privacy controls)
* Exploration (will actually provide metadata for suitable security and privacy controls)

Moreover, the two phases do not really seem to be possible in a *single* API for scripting.

Another argument, a long time ago, was to remove `fetch` from the Scripting API and focus on TDs that are resolved already. Does this argument apply to discovery also.

For example, local discovery via Bluetooth, mDNS, ... don't seem to fit well. An implementation like node-wot might need to provide all different types... does this make sense? OR shall this process be something *out-side* the Scripting API.

Any comments/feedback is welcome!

**Comment by danielpeintner** [comment]
Homework: read [discovery document](https://w3c.github.io/wot-discovery) and come up with 
* use-cases
* requirements
* identify supported methods
* library implementing discovery API? [Discoverer Process](https://w3c.github.io/wot-discovery/#discoverer-process) 
missing?
  * CoAP multicast, see https://github.com/namib-project/node-red-contrib-wot-discovery
* ...

**Comment by egekorkan** [comment]
I have thought quite a bit about this. We are already providing a nice abstraction layer to the protocols via the binding templates that a scripting api implementation sort of depends on in order to define what `readproperty` will do with the given protocol. 
For the next charter, we can work on trying to come up with a similar abstraction layer but for the discovery process of different protocols. These protocols can be CoAP, BacNet, OPC-UA, ROS etc. that have some built-in discovery mechanisms. Each protocol´s binding template specification would then have a section on the discovery process. 
Correspondingly, if the instance of a scripting api implementation contains the discovery implementation of these protocols, calling a certain discovery method starts a discovery process with all the protocols and returns TDs. These TDs most probably have form endpoints that have the same protocol.
To even go further (since writing here is easier than actually implementing this), there are cases where the protocol-specific discovery process protocol specific TD-like formats. We can also specify how these can be automatically transformed into TDs, meaning that a scripting api implementation can return TDs even if the Things do not return TDs.

Disclaimer1: I am indeed aware that this may not be possible with the amount of manpower we currently have.
Disclaimer2: Before coming to scripting, this needs work in architecture, discovery and binding templates specs

**Comment by zolkis** [comment]
@egekorkan that is a good idea, and not necessarily too hard to do in most cases. The (business and technical) use cases for discovery, on which particular IoT protocols implement discovery, are more or less the same or similar. The Scripting API design takes (and should take) these use cases into account, not the protocol specifics.  
So the extension of bindings for discovery would be consistent with the WoT idea, and helpful in standardizing also (parts of) the implementations.
Fortunately this (mostly) affects the Scripting API _implementation_, so IMHO it doesn't directly interfere with this issue (Scripting API conformance class for discovery), though there is an indirect dependency and input from that work.

**Comment by zolkis** [comment]
> The Scripting API design takes (and should take) these use cases into account 

To summarize these. 
Note that the Things that can be discovered by the WoT Scripting API should be in operational mode (i.e. the Thing is provisioned with identity/security, comms configurations, services running etc). Exceptions in section 3.

### 1. Current use cases:
- discover TDs (of operational Things) provided by a directory (URL provided by the script); the resulting TDs can be consumed by the script. (If no URL provided, implementations can use directory discovery/introduction mechanisms, see 3.)
- discover (well, fetch) a TD directly from a URL (provided by the script)

### 2. Use cases out of scope currently, but in scope before.
- discover TDs of (operational) "local" Things, which can be 
     * in the current (or given) IP network/segment, 
     * and/or via Bluetooth/LE, 
     * and/or via NFC (this is unlikely, as it is used mostly for bootstrapping),
     * and/or via USB, 
     * and/or via other local HW interfaces, like SPI, I2C, I2S etc.

### 3. Use cases that have been discussed, but not yet solved.
- introduction mechanism for directories ("discovering directories"). Currently the idea is that this happens when no URL is provided by the script in "directory discovery" mode.
- introduction mechanisms for Things in other than operational mode (to be provisioned, and/or configured): this IMHO should be a different API with a different API entry point (like a management API) and different specification, because of stringent security requirements in many of the protocols, bound to certification processes (e.g. in OCF).
- exposing explicit security options (TBD).
- etc. (feel free to edit this post and add stuff here)

**Comment by relu91** [comment]
> I have thought quite a bit about this. We are already providing a nice abstraction layer to the protocols via the binding templates that a scripting api implementation sort of depends on in order to define what `readproperty` will do with the given protocol. For the next charter, we can work on trying to come up with a similar abstraction layer but for the discovery process of different protocols. These protocols can be CoAP, BacNet, OPC-UA, ROS etc. that have some built-in discovery mechanisms. Each protocol´s binding template specification would then have a section on the discovery process. Correspondingly, if the instance of a scripting api implementation contains the discovery implementation of these protocols, calling a certain discovery method starts a discovery process with all the protocols and returns TDs. These TDs most probably have form endpoints that have the same protocol. To even go further (since writing here is easier than actually implementing this), there are cases where the protocol-specific discovery process protocol specific TD-like formats. We can also specify how these can be automatically transformed into TDs, meaning that a scripting api implementation can return TDs even if the Things do not return TDs.
> 
> Disclaimer1: I am indeed aware that this may not be possible with the amount of manpower we currently have. Disclaimer2: Before coming to scripting, this needs work in architecture, discovery and binding templates specs



> @egekorkan that is a good idea, and not necessarily too hard to do in most cases. The (business and technical) use cases for discovery, on which particular IoT protocols implement discovery, are more or less the same or similar. The Scripting API design takes (and should take) these use cases into account, not the protocol specifics. So the extension of bindings for discovery would be consistent with the WoT idea, and helpful in standardizing also (parts of) the implementations. Fortunately this (mostly) affects the Scripting API _implementation_, so IMHO it doesn't directly interfere with this issue (Scripting API conformance class for discovery), though there is an indirect dependency and input from that work.

I totally agree with the direction here. Indeed early on in this charter, I also tried to expand the direct method to other non-http protocols [here](https://github.com/w3c/wot-discovery/issues/90). Sadly, we couldn't solve the issue and the general agreement was to focus only on HTTP. Next charter is going to be a nice place to start working on this.

**Comment by relu91** [comment]
** call 16/05 **

> exposing explicit security options (TBD).

liked to #390

**Comment by danielpeintner** [comment]
> * We should also add an Editor note about the will to be conformant with https://w3c.github.io/wot-discovery/#discoverer-process. @danielpeintner what do you think?

👍

**Comment by mmccool** [comment]
Added some comments on [issue #321](https://github.com/w3c/wot-scripting-api/issues/321) that maybe should have gone here.  Some further comments:
- Technically WoT Discovery is optional but WoT Architecture says it "should" be supported, and the design does try to address specific issues about privacy, etc.
- It is also possible to support *other* kinds of discovery, i.e. protocol-specific mechanisms defined for CoAP and MQTT.  However, it would be better IMO to work these into the WoT Discovery architecture, as "introduction" mechanisms, rather than as direct mechanisms to broadcast metadata, so we can say something reasonable about access controls, etc.
- WoT Discovery != Thing Description Directories.  Directories are big part of discovery, but everything.  As noted, we put some time into specifying what a "Discoverer" needs to do to implement WoT Discovery.  I think node-wot should seek to satisfy that specification.  We still have a *very short* window to make tweaks to the specification of this process, so would appreciate input if you see any problems implementing the currently specified behaviour for Discoverers in the Scripting API.   See in particular some recently added details about security bootstrapping which relate to the other big discussion item of how to deal with authentication, etc.

**Comment by zolkis** [comment]
Trying to translate that to Scripting API related points (mostly notes to self).

> Technically WoT Discovery is optional

The Scripting discovery API would be always present, but returning error when the functionality is not available.

> Directories are big part of discovery, but are not everything.

Yes. So we need to expose discovery by directories, but also other methods (--> which ones). 

> search for Thing Descriptions (and described Thing instances) that match some specific criteria 

This was covered by filtering in Scripting, currently in need for updating.  

>  there is no standard query language supported in WoT Discovery 

Until then, all filtering has to be local on the client side, as you have pointed out. 
This is the current assumption: only the discovery method will set choices in the implementation.
The [ filtering algorithm ](https://w3c.github.io/wot-scripting-api/#the-start-method) currently is local.

**Comment by mmccool** [comment]
My point about filtering was that it *might* be possible to do it remotely, and when it is possible it is preferred.  So the scripting API should be set up in such a way that if a directory supports queries (which you can find out by looking at its TD) then you should use it, and only do filtering locally as a fallback plan.

The API design should reflect this, by specifying filters in a way that (transparently) allows them to execute remotely if possible.

My other point about filters was that there is no mandatory query mechanism, and there are three different languages possible (technically JSONPath is not normative, though).  So filters should support just simple, least-common-denominator functions that are independent of the query language.  I think one use case for filtering would be searching for TDs including a given @type, another would be searching for a TD with a specific ID, so those should be supported.  It would be nice to have filters that support queries in specific query languages (e.g. SPARQL) but I would expect those to give an error if they can't execute remotely (the other option would be to execute them locally, however... even for SPARQL).

**Comment by mmccool** [comment]
Also, regarding the "which ones" question: there are only two "exploration" mechanisms defined, directories and self-description, and both should be supported.  The real question is which "introduction" mechanisms should be supported.  There is some text in the Discovery spec that gives some minimal requirements, for instance, "direct" is pretty much mandatory, but the others are optional.  I would suggest however at least mDNS-SD would be useful (and would fall into the "local" category).

**Comment by JKRhb** [comment]
Given the new state of the WoT Discovery conformance class, I am wondering if we should close this issue and move the discussion to more specialized issues, for example, one that discusses fleshing out the `discover` method – I suppose this will be the place where we potentially integrate introduction methods like DNS-SD/mDNS, right?

Maybe another issue could be dealing with queries and filtering?
