### ISSUE TITLE
DataSchema type names alignments

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-scripting-api#89]
[ThingPropertyInit](https://w3c.github.io/wot-scripting-api/#the-thingpropertyinit-dictionary) has `DataSchema type`.

[ThingActionInit](https://w3c.github.io/wot-scripting-api/#the-thingactioninit-dictionary) has `DataSchema inputDataDescription` and `DataSchema outputDataDescription`.

[ThingEventInit](https://w3c.github.io/wot-scripting-api/#the-thingeventinit-dictionary) has `DataSchema dataDescription`

In general, this naming does not seem very much aligned and we might want to do some renaming. 

ThingActionInit to `DataSchema typeInput` and `DataSchema typeOutput` and ThingEventInit to `DataSchema type` ?

Anyhow, given that in the TD (https://github.com/w3c/wot-thing-description/issues/66) names are likely to change also I think it is reasonable to align before Prague...

**Comment by zolkis** [comment]
The examples in the TD spec are not aligned with their own definitions. Let's fix naming first in the TD spec and Bindings.

Actions usually have arguments and return something. Keeping that semantics, in `ThingActionInit` I would rather use `arguments` instead of `inputDataDescription`, and `return` instead of `outputDataDescription`.

Events traditionally use `data` property. Therefore in `ThingEventInit` we should use `data`. That is general expectation from developers used with events.

A property usually has name and value. The value has a type. Therefore in `ThingPropertyInit` we could use `type`, `valueType` or simply `schema`.

All of the above are specified as schemas, represented by `DataSchema` which could be string or object (dictionary).

**Comment by mkovatsc** [comment]
Best wait for outcome of naming discussion or participate in https://github.com/w3c/wot-binding-templates/issues/13

**Comment by zolkis** [comment]
Should be fixed by #113
