### ISSUE TITLE
Topics for the Prague F2F 

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-scripting-api#95]
### "TD metadata" representation, TD introspection
  - `.name` (currently exposed read-only)
  - `.base` (base URL) issue #74 
  - `.security`
  - `.interaction` (exposed as `.properties`, `.actions` and `.events`?)

### Semantic annotations
 - provide examples for all supported semantic annotation: issue #97 
 - check how could they be represented in a simpler way

### Type representation
 - issue #89: DataSchema (partially already dealt with)

### Link representation
  - issue #93 (partially already dealt with)

## 2. Security
 - issue #91: security metadata in the API
 - issue #90: error handling (comes when algorithms are defined)

## 3. Next API developments
  - introspection and possibly representation of Properties, Actions and Events. Issue #96

**Comment by zolkis** [comment]
Use the sticky comment above to insert topics.

**Comment by mkovatsc** [comment]
In Prague we will discuss the way forward with a simplified TD that takes Mozilla's requirements into account. This will also have impact on the Scripting API, as new patterns will be enabled.

I am trying to finish a summarizing proposal by March 7 and will distribute it, so that the breakouts can built on that. There will also be a talk on this during the OpenDay.
